blueprint:
  name: Media Player Mute Toggle
  description: Toggle the mute state of a media player.
  domain: script
  input:
    media_player:
      name: Media Player
      description: The media player to toggle mute state
      selector:
        entity:
          multiple: false
          filter:
            - domain: media_player
sequence:
  - target:
      entity_id: "{{ media_player }}"
    action: media_player.volume_mute
    data:
      is_volume_muted: "{{ not state_attr(media_player , 'is_volume_muted') }}"
