blueprint:
  name: Media Player Mute Toggle
  description: Toggle the mute state of a media player.
  domain: script
  input:
    media_player_target:
      name: Media Player
      description: The media player to toggle mute state
      selector:
        entity:
          domain: media_player
          multiple: false

fields:
  otf_media_player:
    name: Media Player (Override)
    description: Override the selected media player with a runtime one
    example: media_player.media_room
    required: false
    selector:
      entity:
        domain: media_player
        multiple: false

variables:
  media_player_target: !input media_player_target
  otf_media_player: "{{ otf_media_player | default('', true) }}"
  my_media_player: >-
    {% if otf_media_player %}
      {{ otf_media_player }}
    {% elif media_player_target %}
      {{ media_player_target }}
    {% else %}
      unknown
    {% endif %}

sequence:
  - service: media_player.volume_mute
    target:
      entity_id: "{{ my_media_player }}"
    data:
      is_volume_muted: >-
        {% set muted = state_attr(my_media_player, 'is_volume_muted') %}
        {{ not muted }}

mode: single
